# Generated by Django 4.0 on 2022-01-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('name', models.CharField(max_length=130, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=130, primary_key=True, serialize=False)),
                ('owned', models.BooleanField(default=False)),
                ('game_status', models.CharField(choices=[('NP', 'Not Planned'), ('WL', 'Waitlisted'), ('OH', 'On Hold'), ('DP', 'Dropped'), ('IP', 'In Progress'), ('FMS', 'Finished Main Story'), ('FMSP', 'Finished Main Story + Extra'), ('CMP', 'Completed'), ('CTN', 'Continuous')], default='NP', max_length=4)),
                ('consoles', models.ManyToManyField(to='game_track_app.Console')),
                ('developers', models.ManyToManyField(to='game_track_app.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('name', models.CharField(max_length=130, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender', models.CharField(max_length=130)),
                ('notes', models.TextField(default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_track_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('review', models.TextField(default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_track_app.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game_track_app.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_track_app.series'),
        ),
    ]
