# Generated by Django 4.0 on 2022-01-02 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_track_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(default='')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_track_app.gamestat')),
            ],
        ),
    ]
